visivo-io/visivo

- tests/parsers/test_schema_generator.py
- visivo/parsers/schema_generator.py
Still included invalid js regex
> Fix schema generation

- tests/models/test_target.py
- visivo/models/target.py
> Catch db error and report

- mkdocs.yml
- mkdocs/overrides/partials/integrations/analytics/combined.html
Copies the existing google stuff and append the hotjar stuff.
> Add hotjar to docs

- .github/workflows/test.yml
- mkdocs.yml
- mkdocs/index.md
- poetry.lock
- pyproject.toml
- visivo/commands/init_phase.py
- visivo/logging/logger.py
In this PR:
Out of scope: 
* Testing for the examples in the docs. 
* Creating out of the box set ups for postgres, mysql & snowflake.
> Fix `Visivo init` & Improve Onboarding Docs

- test-projects/ror/spec/visivo/simple_dashboard_spec.rb
- tests/query/test_trace_tokenizer.py
- visivo/query/trace_tokenizer.py
If the trace has a name, then use that as the cohort on value
> Make the trace name the cohort on value

- .github/workflows/release.yml
- README.md
- mkdocs/index.md
Need to get these flows on main for them to be testable.
> Test releases

- visivo/logging/logger.py
> Add is atty to logger

- .github/workflows/test.yml
- tests/commands/test_serve.py
- visivo/commands/options.py
- visivo/commands/run.py
- visivo/commands/run_phase.py
- visivo/commands/serve.py
- visivo/commands/serve_phase.py
- visivo/logging/logger.py
- visivo/query/runner.py
> Better Query Logs & Query Concurrency

- .github/workflows/deploy_docs.yml
- pyproject.toml
> Tim build docs on tag

- tests/commands/test_version.py
- visivo/command_line.py
> Add version option to the command line

- .github/workflows/deploy_dashoard.yml
- mkdocs/topics/deployments.md
Adds a deploy comment on the PR to the dashboard location.
> Add deploy comment

- tests/parsers/test_serializer.py
- visivo/models/project.py
- visivo/parsers/serializer.py
Start recording this on the project to allow for better debugging and adaptive UI
> Add in cli version to project json

- .mint/deploy_docs.yml
- .mint/test_docs.yml
- mkdocs.yml
- mkdocs/topics/deployments.md
- validate_mkdocs_build.sh
- visivo/commands/deploy.py
- visivo/commands/deploy_phase.py
- visivo/models/trace.py
In this PR-
1.  The macros are compiling correctly 
2.  Speling is currect
> Docs Bug Fix & Set Up Docs CI/CD

- viewer/src/components/Dashboard.js
- viewer/src/components/items/Table.js
> Constrain the table to a max height of the row height

- visivo/models/target.py
To cause the underlying connection to close.
> Set null pool on engine creation

- visivo/models/models/local_merge_model.py
- visivo/models/targets/mysql_target.py
- visivo/models/targets/postgresql_target.py
- visivo/models/targets/sqlite_target.py
documentation
___
- Updated documentation across several files to improve the formatting of notes.
- Enhanced readability and consistency of documentation regarding environment variable usage and local SQLite database limitations.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>local_merge_model.py</strong><dd><code>Improved Note Formatting in LocalMergeModel Documentation</code></dd></summary>
<hr>
visivo/models/models/local_merge_model.py
<li>Updated documentation formatting for notes on local SQLite database <br>usage.<br>
</details>
</td>
<td><a href="https://github.com/visivo-io/visivo/pull/75/files#diff-728f0aba27bb35d16efff382e1917167baf9dbb07daedd010e5 …
> Note fixes in docs

- viewer/src/hooks/useTracesData.js
- viewer/src/models/Trace.js
> Address two issues

- tests/commands/test_init.py
- visivo/commands/init_phase.py
- visivo/models/targets/mysql_target.py
- visivo/models/targets/postgresql_target.py
- visivo/models/targets/snowflake_target.py
- visivo/models/targets/sqlite_target.py
Because CI wasn't running this task because of inputs, it was broken.
> Tim init bug

- viewer/src/components/Dashboard.js
- viewer/src/components/items/Table.js
- visivo/models/models/csv_script_model.py
Will be testing the table name issue in an integration test.
> Couple layout and naming issues

- viewer/src/components/styled/MenuItem.js
> Do not use anchor element

- test-projects/integration/data/aapl_pl.csv
- test-projects/integration/models.visivo.yml
- test-projects/integration/project.visivo.yml
- test-projects/integration/traces.visivo.yml
enhancement
___
- Updated the `waterfall_model` to use the `appl_pl` table and read data from `data/aapl_pl.csv`.
- Changed the dashboard title to "AAPL P&L" and added `waterfallgroupgap` property.
- Modified the `Fibonacci Waterfall` trace to use new data columns and added relevant filters.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>models.visivo.yml</strong><dd><code>Update waterfall model to use AAPL P&L data</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
test-projects/integration/models.visivo.yml
<li>Changed the <code>waterfall_model</code> to use <code>appl_pl</code> …
> Updated waterfall chart to use appl p&l data

- visivo/commands/init_phase.py
enhancement
___
- Updated the repository reference in the `Include` path within the `init_phase` function to point to the `main` branch instead of a specific branch.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>init_phase.py</strong><dd><code>Update repository reference to main branch</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
visivo/commands/init_phase.py
<li>Updated the repository reference in the <code>Include</code> path from a specific <br>branch to the <code>main</code> branch.<br>
</details>
</td>
<td><a href="https://github.com/visivo-io/visivo/pull/92/files#diff- …
> Updated repo reference

- viewer/src/components/items/Chart.js
- viewer/src/components/items/CohortSelect.js
- viewer/src/components/items/CohortSelect.test.js
- viewer/src/components/items/Table.js
- viewer/src/components/items/Table.test.js
- viewer/src/utils/test-utils.js
This is working.  I am having a heck of a time getting any of the tests to work on this one.
I am going to have to just unit test the functions.  🤷 
Video showing the selection, then refresh and how the selection stays.
https://github.com/visivo-io/visivo/assets/482572/1cefff87-043a-4e1e-a26b-1bef38477bd2
> Tim vis 400 have the selection of any of the traces push that value into

- .github/workflows/deploy_dashoard.yml
- .mint/deploy_dashboard.yml
* Test out using the GH command line & Mint Apps. 
* Set up integration test for mint deployment
> Added mint dashboard deploy with commenting

- .mint/deploy_dashboard.yml
- .mint/deploy_docs.yml
- .mint/test_docs.yml
- .mint/test_visivo.yml
- mkdocs/topics/deployments.md
Address deprecation of items in mint
> Tim address rwx migration

- viewer/src/components/styled/Button.js
> Add disabled buttons

- viewer/src/components/items/Chart.js
- viewer/src/components/items/CohortSelect.js
- viewer/src/components/items/CohortSelect.test.js
Fix the display bug I saw in the demo
> Hide menu when select not visible

- test-projects/demo/dashboards/charts.visivo.yml
- viewer/package.json
- viewer/src/Viewer.js
- viewer/src/components/items/CohortSelect.js
- viewer/src/components/items/CohortSelect.test.js
- viewer/src/components/items/Selector.js
- viewer/src/components/styled/BreadcrumbLink.js
- viewer/yarn.lock
This causes all `item.selectors` to always push there state into the URL.  This causes those more global selectors to cause interaction upon load.
> Append selection for item.selector

- tests/commands/test_dist.py
- tests/commands/test_serve_phase.py
- viewer/src/Viewer.js
- viewer/src/components/Home.js
- viewer/src/components/ProjectHistory.js
- viewer/src/components/ProjectHistory.test.js
- visivo/commands/dist_phase.py
- visivo/commands/serve_phase.py
To know when a dashboard was deployed.
> Add timestamp to dashboard

- visivo/commands/dist_phase.py
- visivo/commands/serve_phase.py
Migrated to use the stdlib package
> Remove deprecated pkg_resources

- .mint/test_visivo.yml
- viewer/src/components/Dashboard.js
The viewer won't build into the CLI if you have a lint issue.
> Tim add lint

- .vscode/settings.json
- viewer/src/components/items/Chart.js
- viewer/src/components/items/CohortSelect.js
- viewer/src/models/Trace.js
- viewer/src/models/Trace.test.js
Needed to fix this before doing the row selector
> Tim fix default selection

- test-projects/integration/project.visivo.yml
- viewer/package.json
- viewer/src/components/items/Table.js
- viewer/src/components/items/Table.test.js
- viewer/src/models/Table.js
- viewer/yarn.lock
- visivo/models/table.py
- visivo/models/table_column_definition.py
- visivo/parsers/mkdocs_utils/markdown.py
> Table Improvements

- .github/workflows/deploy_viewer.yml
- .github/workflows/release.yml
Trigger deployments when merge -> development and release -> production
> Add two events when visivo is merged or released

- viewer/src/components/Dashboard.js
- viewer/src/components/Dashboard.test.js
- viewer/src/components/Home.js
- viewer/src/components/Home.test.js
- viewer/src/components/items/Chart.js
- viewer/src/components/select/CohortSelect.test.js
- viewer/src/components/select/NameSelect.js
- viewer/src/components/select/NameSelect.test.js
- viewer/src/contexts/SearchParamsContext.js
- viewer/src/contexts/SearchParamsContext.test.js
- viewer/src/models/Project.js
- viewer/src/utils/test-utils.js
This should resolve many loading errors. The search params were in a race condition and were deleting each other.
> Make a global search params provider

- .vscode/settings.json
- tests/commands/test_deploy_phase.py
- visivo/commands/deploy_phase.py
- visivo/query/query_writer.py
> Tim fix deploy on 1.1 branch

- tests/commands/test_dist.py
- viewer/src/Providers.js
- viewer/src/api/project_history.js
- viewer/src/components/Home.test.js
- viewer/src/components/ProjectHistory.js
- viewer/src/components/ProjectHistory.test.js
- viewer/src/contexts/FetchTracesQueryContext.js
- viewer/src/contexts/QueryContext.js
- viewer/src/hooks/useTracesData.js
- viewer/src/queries/project_history.js
- viewer/src/utils/test-utils.js
- viewer/yarn.lock
- visivo/commands/dist_phase.py
- visivo/commands/serve_phase.py
These are the viewer side changes.
> Tim vis 481 first take on project history viewer

- viewer/src/Providers.js
- viewer/src/api/project_history.js
- viewer/src/components/Home.test.js
- viewer/src/components/ProjectHistory.js
- viewer/src/components/ProjectHistory.test.js
- viewer/src/queries/project_history.js
- viewer/src/utils/test-utils.js
I actually didn't need it here, it was making it hard to handle too.
> Tim fix history link

- .mint/deploy_dashboard.yml
- .mint/deploy_docs.yml
- .mint/test_docs.yml
- .mint/test_visivo.yml
Bring over the work from Tommy
> Tim improve mint usage

- poetry.lock
- pyproject.toml
- test-projects/complex-project/project.visivo.yml
- test-projects/integration/project.visivo.yml
- tests/models/sources/test_postgresql_source.py
- visivo/models/sources/snowflake_source.py
- visivo/models/sources/sqlalchemy_source.py
- visivo/query/jobs/run_trace_job.py
> Improve Snowflake Run & General Run Logging

- tests/commands/test_run.py
- visivo/commands/options.py
- visivo/commands/run_phase.py
- visivo/models/defaults.py
Allows you to set the number of threads at a project level
> Allow threads in defaults

- viewer/src/queries/tracesData.js
- viewer/src/queries/tracesData.test.js
Dan's bug and yours are the same.
> Maintain order from chart object

- visivo/models/defaults.py
- visivo/models/models/sql_model.py
- visivo/models/project.py
These models were allowing anything
> Add forbids to alias configs

- tests/commands/test_compile_phase.py
- tests/commands/test_run_phase.py
- tests/commands/test_serve.py
- tests/commands/test_serve_phase.py
- tests/models/test_dag.py
- tests/query/test_runner.py
- visivo/commands/compile.py
- visivo/commands/compile_phase.py
- visivo/commands/dist.py
- visivo/commands/dist_phase.py
- visivo/commands/options.py
- visivo/commands/run.py
- visivo/commands/run_phase.py
- visivo/commands/serve.py
- visivo/commands/serve_phase.py
- visivo/models/dag.py
- visivo/models/project.py
- visivo/query/runner.py
Changes the name filter to a dag filter with appropriate +'s
> Convert to use the dag filter for compile and run

- tests/query/jobs/test_run_source_connection_job.py
- tests/query/test_runner.py
- visivo/commands/run.py
- visivo/models/sources/source.py
- visivo/query/job_tracker.py
- visivo/query/jobs/job.py
- visivo/query/jobs/run_source_connection_job.py
- visivo/query/runner.py
Add a new handler for connection tests.
> Add connection job to the runner dag.

- viewer/src/contexts/SearchParamsContext.js
- viewer/src/contexts/SearchParamsContext.test.js
Was setting the state incorrectly.
> Selector not clearing default

- tests/factories/model_factories.py
- tests/models/test_project_dag.py
- visivo/models/base/base_model.py
- visivo/models/base/context_string.py
- visivo/models/models/fields.py
- visivo/models/row.py
- visivo/models/selector.py
- visivo/models/sources/fields.py
Searched for references that weren't caught.
> Add context strings to missing locations

- tests/commands/test_test.py
- tests/testing/test_runner.py
- visivo/commands/compile_phase.py
- visivo/commands/deploy_phase.py
- visivo/commands/init_phase.py
- visivo/models/alert.py
- visivo/models/test.py
- visivo/parsers/evaluator.py
We were writing the old names during many processes.  Switched to write the correct name, but the field "if" is a bit special.
> Fix alias on if fields

- visivo/commands/dbt_phase.py
- visivo/models/dashboards/base_dashboard.py
- visivo/models/dbt.py
- visivo/query/jobs/run_thumbnail_job.py
> GUI Editor

- .gitignore
- README.md
- tests/commands/test_init.py
- visivo/commands/dist.py
- visivo/commands/init.py
- visivo/commands/init_phase.py
Make the read me more useful and attractive
> Improve readme

- viewer/src/components/explorer/Explorer.jsx
- viewer/src/components/explorer/QueryPanel.jsx
- viewer/src/stores/explorerStore.js
This fixed the project JSON return type error.  We could make it even better overtime, but this stops errors.
> Cast to string the table items

- visivo/commands/compile_phase.py
- visivo/models/sources/source.py
Need this to allow dbt integration to work since that pulls in extra fields into the model.
> Allow extras for sources

- .github/workflows/release.yml
- visivo/command_line.py
- visivo/commands/init_phase.py
- visivo/models/project.py
- visivo/parsers/serializer.py
- visivo/version.py
> Store version in constant

- tests/parsers/test_schema_generator.py
- visivo/parsers/schema_generator.py
Add a test for a wider string comparison
> Check for query

- viewer/src/components/common/SnackBar.jsx
- viewer/src/components/common/SnackBar.test.jsx
- viewer/src/components/editors/editorPanel/EditorPanel.jsx
- viewer/src/components/editors/editorPanel/modals/TextEditorModal.jsx
1. Introduced a Snackbar (notification) component to display a success message immediately after the system sends the open editor command.
2. Positioned the Snackbar at the top-right corner for better visibility.
3. Ensured the Snackbar appears even if the text editor opens in the background, providing immediate system feedback.
> Lack of system status feedback when when text editor is opened
